sudo: required
services: 
    - docker

before_install:
    - docker build -t ymykai/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true ymykai/react-test npm test

after_success:
    - docker build -t ymykai/multi-client ./client
    - docker build -t ymykai/multi-nginx ./nginx
    - docker build -t ymykai/multi-server ./server
    - docker build -t ymykai/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ymykai/multi-client
    - docker push ymykai/multi-nginx
    - docker push ymykai/multi-server
    - docker push ymykai/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-northeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-northeast-1-138618234684
    bucket_pass: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY